### ISSUE TITLE
Don’t segfault when the CA certificate chains are missing

### ISSUE THREAD

**Issue by andrewshadura** [docker/go-connections#43]
This error is reproducible with 0.3.0:
```
=== RUN   TestConfigServerTLSClientCASet
--- FAIL: TestConfigServerTLSClientCASet (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x548ecb]

goroutine 8 [running]:
testing.tRunner.func1(0xc4200a63c0)
	/usr/lib/go-1.9/src/testing/testing.go:711 +0x2d2
panic(0x58f140, 0x69df40)
	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
crypto/x509.(*CertPool).AddCert(0x0, 0xc4200ea000)
	/usr/lib/go-1.9/src/crypto/x509/cert_pool.go:95 +0x6b
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, 0xc4200e0900, 0x620, 0x820, 0x820)
	/usr/lib/go-1.9/src/crypto/x509/cert_pool.go:128 +0x13a
github.com/docker/go-connections/tlsconfig.certPool(0x5c74d6, 0x2e, 0x5c7100, 0x2c, 0xc4200dca40, 0x1)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/github.com/docker/go-connections/tlsconfig/config.go:105 +0x283
github.com/docker/go-connections/tlsconfig.Server(0x5c74d6, 0x2e, 0x5c728d, 0x2d, 0x5c712d, 0x2c, 0x0, 0x3, 0x0, 0x0, ...)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/github.com/docker/go-connections/tlsconfig/config.go:232 +0x564
github.com/docker/go-connections/tlsconfig.TestConfigServerTLSClientCASet(0xc4200a63c0)
	/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/github.com/docker/go-connections/tlsconfig/config_test.go:175 +0x109
testing.tRunner(0xc4200a63c0, 0x5ca8d8)
	/usr/lib/go-1.9/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/lib/go-1.9/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/docker/go-connections/tlsconfig	0.027s
```
Here's the [full log](https://github.com/docker/go-connections/files/1358374/golang-github-docker-go-connections_0.3.0-1.build.log) (originally at [buildd.debian.org](https://buildd.debian.org/status/package.php?p=golang-github-docker-go-connections&suite=unstable)). See also [Debian bug #871651](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871651)

**Comment by andrewshadura** [comment]
Right, I’ve found the reason: `ca-certificates` package wasn't installed. I guess this situation could have been handled better somehow…

**Comment by thaJeztah** [comment]
I tried to reproduce the panic, but didn't manage to;

Running inside a container, I uninstalled `ca-certificats`;

```bash
apt-get update \
 && apt-get remove -y --purge ca-certificates \
 && apt-get autoremove -y \
 && rm -rf /var/lib/apt/lists/*

ls -l /etc/ssl/certs
ls: cannot access '/etc/ssl/certs': No such file or directory
```

Running tests showed a failure for two tests, but no panic;

```
go test -v ./tlsconfig/
=== RUN   TestConfigServerTLSFailsIfUnableToLoadCerts
--- PASS: TestConfigServerTLSFailsIfUnableToLoadCerts (0.00s)
=== RUN   TestConfigServerTLSServerCertsOnly
--- PASS: TestConfigServerTLSServerCertsOnly (0.00s)
=== RUN   TestConfigServerTLSClientCANotSetIfClientAuthTooLow
--- PASS: TestConfigServerTLSClientCANotSetIfClientAuthTooLow (0.00s)
=== RUN   TestConfigServerTLSClientCASet
--- PASS: TestConfigServerTLSClientCASet (0.00s)
=== RUN   TestConfigServerExclusiveRootPools
    config_test.go:241: Unable to verify certificate 1: x509: certificate signed by unknown authority
--- FAIL: TestConfigServerExclusiveRootPools (0.00s)
=== RUN   TestConfigServerDefaultWithTLSMinimumModifier
--- PASS: TestConfigServerDefaultWithTLSMinimumModifier (0.00s)
=== RUN   TestConfigClientDefaultWithTLSMinimumModifier
--- PASS: TestConfigClientDefaultWithTLSMinimumModifier (0.00s)
=== RUN   TestConfigServerTLSMinVersionIsSetBasedOnOptions
--- PASS: TestConfigServerTLSMinVersionIsSetBasedOnOptions (0.00s)
=== RUN   TestConfigServerTLSMinVersionNotSetIfMinVersionIsTooLow
--- PASS: TestConfigServerTLSMinVersionNotSetIfMinVersionIsTooLow (0.00s)
=== RUN   TestConfigServerTLSMinVersionNotSetIfMinVersionIsInvalid
--- PASS: TestConfigServerTLSMinVersionNotSetIfMinVersionIsInvalid (0.00s)
=== RUN   TestConfigClientTLSNoVerify
--- PASS: TestConfigClientTLSNoVerify (0.00s)
=== RUN   TestConfigClientTLSNoRoot
--- PASS: TestConfigClientTLSNoRoot (0.00s)
=== RUN   TestConfigClientTLSRootCAFileWithOneCert
--- PASS: TestConfigClientTLSRootCAFileWithOneCert (0.00s)
=== RUN   TestConfigClientTLSNonexistentRootCAFile
--- PASS: TestConfigClientTLSNonexistentRootCAFile (0.00s)
=== RUN   TestConfigClientTLSClientCertOrKeyInvalid
--- PASS: TestConfigClientTLSClientCertOrKeyInvalid (0.00s)
=== RUN   TestConfigClientTLSValidClientCertAndKey
--- PASS: TestConfigClientTLSValidClientCertAndKey (0.00s)
=== RUN   TestConfigClientTLSValidClientCertAndEncryptedKey
--- PASS: TestConfigClientTLSValidClientCertAndEncryptedKey (0.00s)
=== RUN   TestConfigClientTLSNotSetWithInvalidPassphrase
--- PASS: TestConfigClientTLSNotSetWithInvalidPassphrase (0.00s)
=== RUN   TestConfigClientExclusiveRootPools
    config_test.go:599: Unable to verify certificate 1: x509: certificate signed by unknown authority
--- FAIL: TestConfigClientExclusiveRootPools (0.00s)
=== RUN   TestConfigClientTLSMinVersionIsSetBasedOnOptions
--- PASS: TestConfigClientTLSMinVersionIsSetBasedOnOptions (0.00s)
=== RUN   TestConfigClientTLSMinVersionNotSetIfMinVersionIsTooLow
--- PASS: TestConfigClientTLSMinVersionNotSetIfMinVersionIsTooLow (0.00s)
=== RUN   TestConfigClientTLSMinVersionNotSetIfMinVersionIsInvalid
--- PASS: TestConfigClientTLSMinVersionNotSetIfMinVersionIsInvalid (0.00s)
FAIL
FAIL	github.com/docker/go-connections/tlsconfig	0.021s
FAIL
```


So I think this is fixed, but feel free to comment if you're still able to reproduce
